# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proba1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from tkinter import Image

from PyQt5 import QtCore, QtGui, QtWidgets
import csv

from PyQt5.QtCore import QDate
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QFileDialog, QMessageBox


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 555)
        MainWindow.setStyleSheet("color: black")


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.name.setStyleSheet(
            "border: 2px solid 'midnightblue';" +
            "border-radius: 8px;" +
            "font-size: 18px;" +
            "color: 'midnightblue';"
        )

        self.verticalLayout.addWidget(self.name)
        self.surname_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.surname_label.setFont(font)
        self.surname_label.setObjectName("surname_label")
        self.verticalLayout.addWidget(self.surname_label)
        self.surname = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.surname.setFont(font)
        self.surname.setObjectName("surname")
        self.surname.setStyleSheet(
            "border: 2px solid 'midnightblue';" +
            "border-radius: 8px;" +
            "font-size: 18px;" +
            "color: 'midnightblue';"
        )

        self.verticalLayout.addWidget(self.surname)
        self.birth_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.birth_label.setFont(font)
        self.birth_label.setObjectName("birth_label")
        self.verticalLayout.addWidget(self.birth_label)
        self.birth = QtWidgets.QDateEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.birth.setFont(font)
        self.birth.setObjectName("birth")
        self.birth.setStyleSheet(
            "border: 2px solid 'midnightblue';" +
            "border-radius: 8px;" +
            "font-size: 18px;" +
            "color: 'midnightblue';"
        )

        self.verticalLayout.addWidget(self.birth)
        self.hospital_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hospital_label.setFont(font)
        self.hospital_label.setObjectName("hospital_label")
        self.verticalLayout.addWidget(self.hospital_label)
        self.hospital = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hospital.setFont(font)
        self.hospital.setObjectName("hospital")
        self.hospital.setStyleSheet(
            "border: 2px solid 'midnightblue';" +
            "border-radius: 8px;" +
            "font-size: 18px;" +
            "color: 'midnightblue';"
        )

        self.hospital.addItem("")
        self.hospital.addItem("")
        self.hospital.addItem("")
        self.verticalLayout.addWidget(self.hospital)
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")

        self.verticalLayout.addWidget(self.info_label)
        self.info = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.info.setStyleSheet(
            "border: 2px solid 'midnightblue';" +
            "border-radius: 8px;" +
            "font-size: 18px;" +
            "color: 'midnightblue';"
        )

        self.verticalLayout.addWidget(self.info)
        self.write_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.write_button.setFont(font)
        self.write_button.setObjectName("write_button")
        self.write_button.setStyleSheet(
                    "*{border: 2px solid midnightblue;" +
                    "border-radius: 10px;" +
                    "font-size: 20px;" +
                    "color: 'midnightblue';" +
                    "padding: 5px 0;" +
                    "margin: 0px 0px}" +
                    "*:hover{background: 'aqua';}"
                                        )

        self.verticalLayout.addWidget(self.write_button)
        self.read_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.read_button.setFont(font)
        self.read_button.setObjectName("read_button")
        self.read_button.setStyleSheet(
            "*{border: 2px solid midnightblue;" +
            "border-radius: 10px;" +
            "font-size: 20px;" +
            "color: 'midnightblue';" +
            "padding: 5px 0;" +
            "margin: 0px 0px}" +
            "*:hover{background: 'aqua';}"
        )

        self.verticalLayout.addWidget(self.read_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.write_button.clicked.connect(self.Write)
        self.read_button. clicked.connect(self.Read)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def Write(self):
        msg = QMessageBox()
        name = self.name.text()
        surname = self.surname.text()
        birth = self.birth.text()
        hospital = self.hospital.currentText()
        info = self.info.text()
        wrong = ""

        if name == "":
            wrong = "empty_name"

        if surname == "":
            wrong = "empty_surname"

        if not name.istitle():
            wrong = "capital_name"

        if not surname.istitle():
            wrong = "capital_surname"

        for word in name:
            if word.isdigit():
                wrong = "digital_in_name"

        for word in surname:
            if word.isdigit():
                wrong = "digital_in_surname"

        if wrong == "digital_in_name":
            msg.setText("Incorrect Name. The name should not contain a number")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        elif wrong == "digital_in_surname":
            msg.setText("Incorrect Surname. The Surname should not contain a number")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        elif wrong == "empty_name":
            msg.setText("Name was not provided")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        elif wrong == "empty_surname":
            msg.setText("Surname was not provided")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        elif wrong == "capital_name":
            msg.setText("Name should be capitalized")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        elif wrong == "capital_surname":
            msg.setText("Surname should be capitalized")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()
        else:
            fname = QFileDialog.getSaveFileName(None, 'Save file',
                                                'c:\\', "CSV files (*.csv)")
            fname = fname[0]
            file = open(fname, 'w')

            dialect = csv.excel
            dialect.delimiter = ";"

            csv_writer = csv.DictWriter(file, ['Name',
                                               'Surname',
                                               'Date of Birth',
                                               'Hospital',
                                               'Additional Information'], dialect=dialect)
            csv_writer.writeheader()

            csv_writer.writerow({
                    'Name': name,
                    'Surname': surname,
                    'Date of Birth': birth,
                    'Hospital': hospital,
                    'Additional Information': info
            })

            file.close()

    def Read(self):
        dialect = csv.excel
        dialect.delimiter = ";"


        fname = QFileDialog.getOpenFileName(None, 'Open file',
                                            'c:\\', "CSV file (*.csv)")
        fname = fname[0]
        file = open(fname, 'r')
        attendes = []

        csv_file = csv.reader(file, dialect=dialect)

        for row in csv_file:
            attendes.append(row)

        attendes_row = attendes[2]
        date = attendes_row[2].replace(".", ",")
        date2 = []
        word = ""

        for letter in date:
            if letter == ",":
                date2.append(word)
                word = ""
            else:
                word = word + letter
        date2.append(word)

        self.name.setText(attendes_row[0])
        self.surname.setText(attendes_row[1])
        self.birth.setDate(QDate(int(date2[2]), int(date2[1]), int(date2[0])))
        self.hospital.setCurrentText(attendes_row[3])
        self.info.setText(attendes_row[4])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.surname_label.setText(_translate("MainWindow", "Surname:"))
        self.birth_label.setText(_translate("MainWindow", "Date of Birth:"))
        self.hospital_label.setText(_translate("MainWindow", "Hospital:"))
        self.hospital.setItemText(0, _translate("MainWindow", "Borowska Szpital"))
        self.hospital.setItemText(1, _translate("MainWindow", "Szpital na Kaminskiego"))
        self.hospital.setItemText(2, _translate("MainWindow", "Koszarowa Szpital"))
        self.info_label.setText(_translate("MainWindow", " Information about chronic diseases:"))
        self.write_button.setText(_translate("MainWindow", "Write"))
        self.read_button.setText(_translate("MainWindow", "Read"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())